# -*- coding: utf-8 -*-
"""
Created on Wed Mar 01 11:11:16 2017

@author: wcrum
"""


# Generated by: ukb_conv.exe ukb8546.enc_ukb doc
namehtml = 'Z:\EABOAGYE\Users\wcrum\Projects\UKBB\UKBB-data\ukb8546.html'
# Generated by: ukb_conv.exe ukb8546.enc_ukb csv
namecsv = 'Z:\EABOAGYE\Users\wcrum\Projects\UKBB\UKBB-data\ukb8546.csv'

N=50

import BiobankRead2 as bb2



